Update: true

Tab:
  Enable: true
  Cooldown: 5
  #单位:秒
  Tab: "%player_name%"
Tablist:
  Enable: true
  Cooldown: 5
  #单位:秒
  Header: |-
    &7
    &7&e欢迎您，%player_name%&7&r
    &7
  Footer: |-
    &7
    &e您有%playerpoints_points%点券
    &7
