name: EasyTab
main: github.azurehanchen.Tab
version: 1.1.0
author: AzureHanChen
depend: [ProtocolLib]
softdepend: [PlaceholderAPI]
commands:
  easytab:
permissions:
    easytab.admin:
        default: op